[package]
authors = ["Richard Cook"]
description = "Git URL parser"
homepage = "https://github.com/rcook/joatmon-rs/"
license = "MIT"
name = "joat-git-url"
version = "0.0.1"
edition = "2021"

[dependencies]
